version: '3.1'

services:
  db:
    build: .
    container_name: curso-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=curso-db